name: Generate GitBlog README
on:
  workflow_dispatch:  # 手动触发（可选）
  issues:
    types: [opened, edited]  # 当 Issue 被创建或编辑时自动运行
  push:
    branches:
      - main
    paths:
      - main.py  # 当 main.py 有更改时自动运行

jobs:
  sync:
    name: Generate README
    runs-on: ubuntu-latest
    # 条件：仅在 push 事件或 owner 是触发 Issue 的用户时运行
    if: ${{ github.event_name == 'push' || (github.event_name == 'issues' && github.repository_owner_id == github.event.issue.user.id) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 更新到较新版本，3.8 已较老
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Generate new md
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}  # 将 Issue 编号设为环境变量
        run: |
          # 激活虚拟环境（已在上一节激活，这里保留一致性）
          source venv/bin/activate
          # 根据是否有 Issue 编号动态调用 main.py
          if [ -n "$ISSUE_NUMBER" ]; then
            python main.py "${{ secrets.G_T }}" "${{ github.repository }}" --issue_number "$ISSUE_NUMBER"
          else
            python main.py "${{ secrets.G_T }}" "${{ github.repository }}"
          fi

      - name: Push README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Blog/*.md
          git commit -a -m "Update blog from ${{ github.event_name }}" || echo "Nothing to commit"
          git push || echo "Nothing to push"
